# benchmark should be one of the "similarity","family","function","affinity","all"
benchmark: similarity 
# Path of the representation file for "similarity","family","function" tasks
representation_file_human: /media/DATA/serbulent/DATA/Thesis/ReviewPaper/results/representation_vectors/representation_vector_dataframes/revision-1/APAAC_UNIPROT_HUMAN.csv
# Path of the representation file for affinity task
representation_file_affinity: /media/DATA/serbulent/DATA/Thesis/ReviewPaper/results/representation_vectors/representation_vector_dataframes/skempi/pdb_apaac_dim80.csv
# Representation name
representation_name: APAAC
# similarity_tasks should be a list can be include any combination of "Sparse","200","500"
similarity_tasks: ["Sparse","200","500"]
# function_prediction_aspect should be one of the "MF","BP","CC","All_Aspects"
function_prediction_aspect: All_Aspects
# function_prediction_dataset should be one of the "High","Middle","Low","All_Data_Sets"
function_prediction_dataset: All_Data_Sets
#detailed_output can be True or False
detailed_output: True
